#!/bin/sh

#create tun
mkdir -p /dev/net
mknod /dev/net/tun c 10 200

#check if set custom config:
if [[ $CUSTOM_CFG == "yes" ]]
then
        exec /usr/sbin/openvpn --config /data/$CONFIG_FILE
fi
if [[ $CUSTOM_CFG == "no" ]]
then
        if [[ $FLOAT == "yes" ]]
        then
                float='float'
        elif [[ $FLOAT == "no" ]]
        then
                float='#float'
        fi
        echo '### Autogenerated '$CONFIG_NAME'.conf ###
remote '$REMOTE_IP'
'$float'
port '$PORT'
dev tun
ifconfig '$TUN_LOCAL_IP' '$TUN_REMOTE_IP'
compress stub-v2
push "compress stub-v2"
keepalive 10 60
ping-timer-rem
persist-tun
verb 3
secret /data/'$KEY'
persist-key
cipher AES-256-CBC
auth-nocache
'$ROUTES'
user nobody
group nobody
chroot /var/empty
log /data/'$LOG_NAME'
log-append /data/'$LOG_NAME'' > /data/$CONFIG_NAME.conf
        exec /usr/sbin/openvpn --config /data/$CONFIG_NAME.conf
fi
