version: '3.5'
services:
    onvpn2:
        image: ovpn:2.0
        container_name: ovpn_2_0
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        environment:
            - CUSTOM_CFG=no #Mandatory yes|no
            - CONFIG_FILE=test.conf #Mandatory if custom_cfg=yes
            - REMOTE_IP=1.1.1.1 #from here, mandatory if custom_cfg=no
            - FLOAT=no #yes|no
            - PORT=9001
            - TUN_LOCAL_IP=10.9.9.1
            - TUN_REMOTE_IP=10.9.9.2
            - KEY=key_test.key
            - ROUTES=route 192.168.111.0 255.255.255.0
            - LOG_NAME=prueba.log
            - CONFIG_NAME=prueba
        volumes:
            - /opt/docker_data/ovpn:/data
        ports:
            - 9001/udp
        networks:
            ovpn_bridge:
              ipv4_address: 192.0.0.101
networks:
  ovpn_bridge:
    name: docker2
    driver: bridge
    ipam:
      config:
        - subnet: 192.0.0.0/24
    driver_opts:
      com.docker.network.bridge.name: docker2
